clc;clear;close;
imds = imageDatastore('C:\Users\aaj21\OneDrive - City, University of London\Computer Vision-LAPTOP-O8A4BGK3\Coursework\Augmented ImagesColorv2\', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames'); 
[imdsTrain,imdsValidation] = splitEachLabel(imds,0.8,'randomize');
%{
imageAugmenter = imageDataAugmenter( ...
    'RandXReflection',true,...
    'RandRotation',[-20,20], ...
    'RandScale',[0.2 1],...
    'RandXTranslation',[-30 30], ...
    'RandYTranslation',[-30 30])
%}

imageAugmenter = imageDataAugmenter( ...
    'RandXTranslation',[-5 5], ...
    'RandYTranslation',[-5 5])

augimdsTrain = augmentedImageDatastore([227 227],imdsTrain,'DataAugmentation',imageAugmenter);
augimdsValidation = augmentedImageDatastore([227 227],imdsValidation);